from cage_pinn.pdes.base import PDEProblem
from cage_pinn.pdes.extended import (
    Advection1D,
    AdvectionDiffusion1D,
    AllenCahn1D,
    Burgers1D,
    Helmholtz2D,
    HeterogeneousPoisson1D,
    HighFrequencyHelmholtz2D,
    KovasznayFlow,
    LidDrivenCavity,
    LidDrivenCavityRe1000,
    LidDrivenCavityRe3200,
    Poisson10D,
    TaylorGreenVortex,
    Wave1D,
    WeakSharpAdvection,
)
from cage_pinn.pdes.problems import (
    CoupledOscillator,
    Heat1D,
    Poisson1D,
    create_problem,
    problem_registry,
)

__all__ = [
    "Advection1D",
    "AdvectionDiffusion1D",
    "AllenCahn1D",
    "Burgers1D",
    "CoupledOscillator",
    "Heat1D",
    "Helmholtz2D",
    "HeterogeneousPoisson1D",
    "HighFrequencyHelmholtz2D",
    "KovasznayFlow",
    "LidDrivenCavity",
    "LidDrivenCavityRe1000",
    "LidDrivenCavityRe3200",
    "PDEProblem",
    "Poisson1D",
    "Poisson10D",
    "TaylorGreenVortex",
    "Wave1D",
    "WeakSharpAdvection",
    "create_problem",
    "problem_registry",
]
