from __future__ import annotations

import hashlib
import re
from pathlib import Path
from typing import Any

import pandas as pd

SCHEMA = (
    "canonical_title",
    "authors",
    "year",
    "date",
    "venue",
    "doi",
    "external_identifier",
    "peer_review_status",
    "source_urls",
    "full_text_access_status",
    "problem_class",
    "method_family",
    "exact_methodological_change",
    "controller_signal",
    "adapted_object",
    "reference_solution_required_during_training",
    "compute_overhead",
    "architecture_dependence",
    "supported_pde_types",
    "assumptions",
    "central_claim",
    "reported_advantages",
    "reported_disadvantages",
    "limitations_stated_by_authors",
    "limitations_inferred_by_us",
    "benchmarks",
    "seed_count",
    "comparator_quality",
    "compute_fairness_quality",
    "ablation_quality",
    "code_url",
    "code_license",
    "relation_to_cage",
    "collision_severity",
    "supporting_pointer",
    "extraction_status",
)


def _paper(**values: Any) -> dict[str, Any]:
    defaults: dict[str, Any] = {
        "date": "",
        "venue": "",
        "doi": "",
        "external_identifier": "",
        "peer_review_status": "not verified",
        "source_urls": "",
        "full_text_access_status": "abstract/metadata checked",
        "problem_class": "multiple",
        "method_family": "",
        "exact_methodological_change": "",
        "controller_signal": "none identified",
        "adapted_object": "",
        "reference_solution_required_during_training": "no",
        "compute_overhead": "not extracted",
        "architecture_dependence": "not extracted",
        "supported_pde_types": "not extracted",
        "assumptions": "not extracted",
        "central_claim": "",
        "reported_advantages": "not extracted",
        "reported_disadvantages": "not extracted",
        "limitations_stated_by_authors": "not extracted",
        "limitations_inferred_by_us": "Requires independent full-text audit before claim use.",
        "benchmarks": "not extracted",
        "seed_count": "not extracted",
        "comparator_quality": "not audited",
        "compute_fairness_quality": "not audited",
        "ablation_quality": "not audited",
        "code_url": "",
        "code_license": "not verified",
        "relation_to_cage": "",
        "collision_severity": 3,
        "supporting_pointer": "abstract/metadata unless otherwise stated",
        "extraction_status": "screened; full extraction incomplete",
    }
    defaults.update(values)
    missing = {"canonical_title", "authors", "year"} - defaults.keys()
    if missing:
        raise ValueError(f"Missing required paper fields: {missing}")
    return {field: defaults.get(field, "") for field in SCHEMA}


def seed_records() -> list[dict[str, Any]]:
    """Verified metadata seed, not an exhaustive systematic-review corpus."""
    return [
        _paper(
            canonical_title="Artificial neural networks for solving ordinary and partial differential equations",
            authors="I. E. Lagaris; A. Likas; D. I. Fotiadis",
            year=1998,
            venue="IEEE Transactions on Neural Networks",
            doi="10.1109/72.712178",
            peer_review_status="journal",
            source_urls="https://doi.org/10.1109/72.712178",
            method_family="pre-PINN neural differential-equation solver; hard constraints",
            exact_methodological_change="Trial functions satisfy boundary conditions by construction and a neural network minimizes differential-equation error.",
            adapted_object="architecture; hard constraint",
            relation_to_cage="Foundational, orthogonal to audit-guided allocation.",
            collision_severity=3,
        ),
        _paper(
            canonical_title="Physics-informed neural networks: A deep learning framework for solving forward and inverse problems involving nonlinear partial differential equations",
            authors="Maziar Raissi; Paris Perdikaris; George Em Karniadakis",
            year=2019,
            venue="Journal of Computational Physics",
            doi="10.1016/j.jcp.2018.10.045",
            peer_review_status="journal",
            source_urls="https://doi.org/10.1016/j.jcp.2018.10.045",
            full_text_access_status="open manuscript/metadata available",
            method_family="continuous/discrete-time PINN",
            exact_methodological_change="Uses automatic differentiation and PDE residual losses for forward and inverse problems.",
            adapted_object="base formulation",
            relation_to_cage="Parent formulation; no cross-fitted enforcement controller.",
            collision_severity=3,
            code_url="https://github.com/maziarraissi/PINNs",
        ),
        _paper(
            canonical_title="Understanding and mitigating gradient flow pathologies in physics-informed neural networks",
            authors="Sifan Wang; Yujun Teng; Paris Perdikaris",
            year=2021,
            venue="SIAM Journal on Scientific Computing",
            doi="10.1137/20M1318043",
            peer_review_status="journal",
            source_urls="https://doi.org/10.1137/20M1318043",
            method_family="optimization pathology; loss weighting",
            exact_methodological_change="Diagnoses imbalanced loss gradients and proposes learning-rate annealing plus an architecture modification.",
            controller_signal="training-loss gradient statistics",
            adapted_object="loss weights; architecture",
            relation_to_cage="Overlaps gradient diagnostics, but uses training objectives rather than unseen physics audit folds.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="When and why PINNs fail to train: A neural tangent kernel perspective",
            authors="Sifan Wang; Xinling Yu; Paris Perdikaris",
            year=2022,
            venue="Journal of Computational Physics",
            external_identifier="arXiv:2007.14527",
            peer_review_status="journal",
            source_urls="https://arxiv.org/abs/2007.14527",
            method_family="NTK analysis; loss weighting",
            exact_methodological_change="Uses PINN NTK dynamics to explain convergence-rate imbalance and adapt loss weights.",
            controller_signal="training NTK convergence rates",
            adapted_object="loss weights",
            relation_to_cage="Training-dynamics weighting, not audit-risk selection among enforcement forms.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Characterizing possible failure modes in physics-informed neural networks",
            authors="Aditi Krishnapriyan; Amir Gholami; Shandian Zhe; Robert M. Kirby; Michael W. Mahoney",
            year=2021,
            venue="NeurIPS",
            peer_review_status="conference",
            source_urls="https://arxiv.org/abs/2109.01050",
            method_family="failure modes; curriculum",
            exact_methodological_change="Diagnoses optimization failures and studies curriculum strategies.",
            adapted_object="training schedule",
            relation_to_cage="Motivates robust diagnostics but does not implement cross-fitted audit allocation.",
            collision_severity=3,
        ),
        _paper(
            canonical_title="A comprehensive study of non-adaptive and residual-based adaptive sampling for physics-informed neural networks",
            authors="Colby L. Wight; Jia Zhao",
            year=2023,
            venue="Computer Methods in Applied Mechanics and Engineering",
            doi="10.1016/j.cma.2022.115671",
            peer_review_status="journal",
            source_urls="https://doi.org/10.1016/j.cma.2022.115671",
            method_family="adaptive collocation; RAR-D/RAD",
            exact_methodological_change="Compares fixed and residual-proportional adaptive collocation strategies.",
            controller_signal="candidate-point training residual magnitude",
            adapted_object="points",
            relation_to_cage="Overlaps fresh coverage and off-grid candidate residual evaluation; selects location, not enforcement form.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Mitigating propagation failures in physics-informed neural networks using Retain-Resample-Release (R3) sampling",
            authors="Arka Daw; Jie Bu; Sifan Wang; Paris Perdikaris; Anuj Karpatne",
            year=2023,
            external_identifier="arXiv:2207.02338",
            peer_review_status="conference/journal status not rechecked",
            source_urls="https://arxiv.org/abs/2207.02338",
            method_family="adaptive collocation; causal sampling",
            exact_methodological_change="Retains high-residual points, resamples others, and provides a causal extension.",
            controller_signal="training residual distribution",
            adapted_object="points",
            relation_to_cage="Selects locations from residuals, not S/J/W forms from cross-fitted audit utility.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Gradient-enhanced physics-informed neural networks for forward and inverse PDE problems",
            authors="Jeremy Yu; Lu Lu; Xuhui Meng; George Em Karniadakis",
            year=2022,
            external_identifier="arXiv:2111.02801",
            peer_review_status="journal status not rechecked",
            source_urls="https://arxiv.org/abs/2111.02801",
            method_family="residual-gradient; Sobolev/double backpropagation",
            exact_methodological_change="Adds spatial derivatives of the PDE residual to the training objective.",
            controller_signal="none; static objective",
            adapted_object="formulation",
            compute_overhead="higher-order automatic differentiation",
            relation_to_cage="CAGE J is a known gPINN-family primitive; only the audit-guided allocation is under study.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="RoPINN: Region Optimized Physics-Informed Neural Networks",
            authors="Haixu Wu; Huakun Luo; Yuezhou Ma; Jianmin Wang; Mingsheng Long",
            year=2024,
            venue="NeurIPS 2024",
            doi="10.52202/079017-3508",
            external_identifier="arXiv:2405.14369",
            peer_review_status="conference",
            source_urls="https://proceedings.neurips.cc/paper_files/paper/2024/hash/c745bfa5b50544882938ff4f89ff26ac-Abstract-Conference.html;https://arxiv.org/abs/2405.14369",
            full_text_access_status="open full text",
            method_family="region optimization; generalization",
            exact_methodological_change="Optimizes Monte Carlo neighborhoods and adapts trust-region size from gradient variance.",
            controller_signal="successive training-gradient variance",
            adapted_object="sampling neighborhood",
            relation_to_cage="Closest generalization-oriented plug-in; no separated cross-fitted audit or S/J/W allocation.",
            collision_severity=2,
            code_url="https://github.com/thuml/RoPINN",
        ),
        _paper(
            canonical_title="PINNACLE: PINN Adaptive ColLocation and Experimental points selection",
            authors="Gregory Kang Ruey Lau; Apivich Hemachandra; See-Kiong Ng; Bryan Kian Hsiang Low",
            year=2024,
            venue="ICLR 2024",
            external_identifier="arXiv:2404.07662",
            peer_review_status="conference",
            source_urls="https://proceedings.iclr.cc/paper_files/paper/2024/hash/3e8d9bf1dd1eb9d3d9d500fb3543c87b-Abstract-Conference.html;https://arxiv.org/abs/2404.07662",
            full_text_access_status="open full text",
            method_family="adaptive point selection; NTK",
            exact_methodological_change="Jointly selects collocation and experimental point types using interactions derived from PINN NTK dynamics.",
            controller_signal="training-point interaction/NTK criterion",
            adapted_object="points; proportions of point types",
            relation_to_cage="Close cost-allocation question, but allocates point types rather than strong/gradient/weak formulations and lacks audit roles.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="ConFIG: Towards Conflict-free Training of Physics Informed Neural Networks",
            authors="Qiang Liu; Mengyu Chu; Nils Thuerey",
            year=2025,
            venue="ICLR 2025",
            external_identifier="arXiv:2408.11104",
            peer_review_status="conference",
            source_urls="https://proceedings.iclr.cc/paper_files/paper/2025/hash/94e85561a342de88b559b72c9b29f638-Abstract-Conference.html;https://arxiv.org/abs/2408.11104",
            full_text_access_status="open full text",
            method_family="gradient conflict; optimizer",
            exact_methodological_change="Constructs updates with positive dot products to loss-specific training gradients.",
            controller_signal="training-loss gradient conflict",
            adapted_object="optimizer update",
            relation_to_cage="Shares gradient alignment mathematics but CAGE aligns learner atoms with a selector-audit gradient and debits cost.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Gradient Alignment in Physics-informed Neural Networks: A Second-Order Optimization Perspective",
            authors="Sifan Wang; Ananyae Kumar Bhartari; Bowen Li; Paris Perdikaris",
            year=2025,
            external_identifier="arXiv:2502.00604",
            peer_review_status="preprint status checked 2026-07-24",
            source_urls="https://arxiv.org/abs/2502.00604",
            method_family="gradient alignment; second-order optimization",
            controller_signal="training-loss gradients",
            adapted_object="optimizer/preconditioner",
            relation_to_cage="Motivates optimizer conditioning; no unseen-audit enforcement selection identified.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Variational Physics-Informed Neural Networks for Solving Partial Differential Equations",
            authors="Ehsan Kharazmi; Zhongqiang Zhang; George Em Karniadakis",
            year=2019,
            external_identifier="arXiv:1912.00873",
            peer_review_status="preprint/journal status not rechecked",
            source_urls="https://arxiv.org/abs/1912.00873",
            method_family="weak/variational PINN",
            exact_methodological_change="Enforces variational residuals against test functions.",
            controller_signal="none; static formulation",
            adapted_object="formulation",
            relation_to_cage="CAGE W is in the established weak/variational family.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="XPINNs: A generalized space-time domain decomposition based deep learning framework for nonlinear partial differential equations",
            authors="Ameya D. Jagtap; George Em Karniadakis",
            year=2020,
            venue="Communications in Computational Physics",
            external_identifier="arXiv:2004.11643",
            peer_review_status="journal",
            source_urls="https://arxiv.org/abs/2004.11643",
            method_family="domain decomposition",
            exact_methodological_change="Uses subdomain networks with solution and residual/interface coupling.",
            adapted_object="domain; architecture",
            relation_to_cage="Parent backbone; CAGE must preserve its partition and parameter budget.",
            collision_severity=3,
        ),
        _paper(
            canonical_title="AB-PINNs: Adaptive-Basis Physics-Informed Neural Networks for Residual-Driven Domain Decomposition",
            authors="Jonah Botvinick-Greenhouse; Wael H. Ali; Mouhacine Benosman; Saviz Mowlavi",
            year=2025,
            external_identifier="arXiv:2510.08924",
            peer_review_status="preprint",
            source_urls="https://arxiv.org/abs/2510.08924;https://github.com/merlresearch/ab-pinns",
            full_text_access_status="open full text and official code located",
            method_family="adaptive basis; domain decomposition",
            exact_methodological_change="Moves/deforms local bases and optionally adds subdomains using residual loss.",
            controller_signal="training residual",
            adapted_object="domain; basis; architecture",
            relation_to_cage="Parent backbone; CAGE cannot control subdomain addition asymmetrically.",
            collision_severity=3,
            code_url="https://github.com/merlresearch/ab-pinns",
        ),
        _paper(
            canonical_title="PINNacle: A Comprehensive Benchmark of Physics-Informed Neural Networks for Solving PDEs",
            authors="Zhongkai Hao; Jiachen Yao; Chang Su; Hang Su; Ziao Wang; Fanzhi Lu; Zeyu Xia; Yichi Zhang; Songming Liu; Lu Lu; Jun Zhu",
            year=2024,
            venue="NeurIPS 2024 Datasets and Benchmarks",
            doi="10.52202/079017-2442",
            peer_review_status="conference benchmark track",
            source_urls="https://proceedings.neurips.cc/paper_files/paper/2024/hash/8c63299fb2820ef41cb05e2ff11836f5-Abstract-Datasets_and_Benchmarks_Track.html",
            method_family="benchmark",
            adapted_object="evaluation suite",
            relation_to_cage="Benchmark and comparator source; distinct from PINNACLE point selection.",
            collision_severity=3,
        ),
        _paper(
            canonical_title="Residual-based error bound for physics-informed neural networks",
            authors="Shuheng Liu; Xiyue Huang; Pavlos Protopapas",
            year=2023,
            venue="UAI / PMLR 216",
            peer_review_status="conference",
            source_urls="https://proceedings.mlr.press/v216/liu23b.html",
            full_text_access_status="open full text",
            method_family="residual certification; error bounds",
            exact_methodological_change="Relates residual estimates to solution error under problem-dependent assumptions.",
            adapted_object="post-training certification",
            relation_to_cage="Theory neighbor; CAGE's bounded audit score alone is not a solution-error certificate.",
            collision_severity=3,
        ),
        _paper(
            canonical_title="PINNs Failure Modes are Overfitting",
            authors="Nigel T. Andersen; Takashi Matsubara",
            year=2026,
            date="2026-05-29",
            external_identifier="arXiv:2605.30910",
            peer_review_status="preprint",
            source_urls="https://arxiv.org/abs/2605.30910",
            full_text_access_status="open abstract/full text available",
            method_family="residual overfitting; double backpropagation",
            exact_methodological_change="Diagnoses collocation overfitting and extends residual double-backpropagation as a static remedy.",
            controller_signal="off-grid residual used diagnostically; no online allocation identified in abstract screening",
            adapted_object="regularization/formulation",
            relation_to_cage="Closest motivation and J primitive; no cross-fitted S/J/W controller identified.",
            collision_severity=2,
            extraction_status="abstract and metadata screened; full-text collision audit required",
        ),
        _paper(
            canonical_title="Rigorous Error Certification for Neural PDE Solvers: From Empirical Residuals to Solution Guarantees",
            authors="Amartya Mukherjee; Maxwell Fitzsimmons; David C. Del Rey Fernández; Jun Liu",
            year=2026,
            date="2026-03-19",
            external_identifier="arXiv:2603.19165",
            peer_review_status="preprint",
            source_urls="https://arxiv.org/abs/2603.19165",
            full_text_access_status="open abstract/full text available",
            method_family="rigorous residual-to-solution certification",
            exact_methodological_change="Derives deterministic/probabilistic residual, boundary, and initial-error bounds under compactness/stability assumptions.",
            adapted_object="certification",
            relation_to_cage="Constrains theory wording; complementary to online allocation.",
            collision_severity=3,
        ),
        _paper(
            canonical_title="Goal oriented error estimation for adaptive sampling of PINNS",
            authors="Medard Govoeyi; Thomas Richter",
            year=2026,
            date="2026-04-02",
            external_identifier="arXiv:2604.01835",
            peer_review_status="preprint",
            source_urls="https://arxiv.org/abs/2604.01835",
            full_text_access_status="open abstract/full text available",
            method_family="goal-oriented/DWR adaptive sampling",
            exact_methodological_change="Uses a neural DWR estimator to importance-sample points for a quantity of interest.",
            controller_signal="goal-error estimator",
            adapted_object="points",
            relation_to_cage="Selects locations for a target functional, not enforcement forms from unseen residual risk.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Random test functions, H^{-1} norm equivalence, and stochastic variational physics-informed neural networks",
            authors="Diego Marcondes",
            year=2026,
            date="2026-05-05",
            external_identifier="arXiv:2605.03542",
            peer_review_status="preprint",
            source_urls="https://arxiv.org/abs/2605.03542",
            full_text_access_status="open abstract/full text available",
            method_family="stochastic weak/variational PINN",
            exact_methodological_change="Establishes an H^-1 norm equivalence using random test functions and trains with stochastic variational residuals.",
            controller_signal="none identified; weak objective",
            adapted_object="formulation; test functions",
            relation_to_cage="Strong overlap with W; CAGE makes no novelty claim for W.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Diversity-Aware Adaptive Collocation for Physics-Informed Neural Networks via Sparse QUBO Optimization and Hybrid Coresets",
            authors="not fully extracted",
            year=2026,
            date="2026-03",
            external_identifier="arXiv:2603.06761",
            peer_review_status="preprint",
            source_urls="https://arxiv.org/abs/2603.06761",
            method_family="adaptive collocation; diversity; coresets",
            adapted_object="points",
            relation_to_cage="Location/diversity adaptation, not audited form selection.",
            collision_severity=2,
        ),
        _paper(
            canonical_title="Evolutionary Algorithm-Guided LLMs for Physics-Informed Neural Network Design",
            authors="not fully extracted",
            year=2026,
            date="2026-07",
            external_identifier="arXiv:2607.15560",
            peer_review_status="preprint",
            source_urls="https://arxiv.org/abs/2607.15560",
            method_family="automatic algorithm/architecture discovery",
            adapted_object="design/architecture",
            relation_to_cage="Meta-design neighbor; not an online cross-fitted residual controller based on abstract screening.",
            collision_severity=3,
        ),
        _paper(
            canonical_title="From PINNs to PIKANs: Recent Advances in Physics-Informed Machine Learning",
            authors="Juan Diego Toscano; Vivek Oommen; Alan John Varghese; Zongren Zou; Nazanin Ahmadi Daryakenari; Chenxi Wu; George Em Karniadakis",
            year=2024,
            external_identifier="arXiv:2410.13228",
            peer_review_status="survey preprint",
            source_urls="https://arxiv.org/abs/2410.13228",
            full_text_access_status="open full text",
            method_family="survey/taxonomy",
            adapted_object="review",
            relation_to_cage="Seed survey for backward snowballing; not a collision.",
            collision_severity=3,
        ),
    ]


def _normalized_title(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "", value.lower())


def _dedup_key(row: pd.Series) -> str:
    doi = str(row.get("doi", "")).strip().lower()
    identifier = str(row.get("external_identifier", "")).strip().lower()
    if doi:
        return f"doi:{doi}"
    if identifier:
        return f"id:{identifier}"
    return f"title:{_normalized_title(str(row['canonical_title']))}:{int(row['year'])}"


def build_corpus(directory: str | Path = "research/literature") -> dict[str, Any]:
    target = Path(directory)
    target.mkdir(parents=True, exist_ok=True)
    frame = pd.DataFrame(seed_records(), columns=SCHEMA)
    frame["_dedup_key"] = frame.apply(_dedup_key, axis=1)
    duplicates = frame[frame.duplicated("_dedup_key", keep=False)]
    if not duplicates.empty:
        titles = duplicates["canonical_title"].tolist()
        raise ValueError(f"Literature corpus contains duplicate identities: {titles}")
    frame = frame.drop(columns=["_dedup_key"]).sort_values(
        ["year", "canonical_title"], kind="stable"
    )
    csv_path = target / "papers.csv"
    parquet_path = target / "papers.parquet"
    frame.to_csv(csv_path, index=False)
    frame.to_parquet(parquet_path, index=False)
    digest = hashlib.sha256(csv_path.read_bytes()).hexdigest()
    return {
        "records": len(frame),
        "csv": str(csv_path),
        "parquet": str(parquet_path),
        "sha256": digest,
        "status": "seed corpus; systematic expansion and independent full-text review pending",
    }

